
FROM oven/bun:1

WORKDIR /usr/src/app
ARG DATABASE_URL

COPY ./packages  ./packages 
COPY ./bun.lock ./bun.lock 

COPY ./apps/web ./apps/web
COPY . .

RUN bun install
RUN bunx prisma generate --schema=packages/db/prisma/schema.prisma
RUN bun run build

EXPOSE 8080

CMD [ "bun" , "run", "start:web" ]